name: first_manna_poultry_farm
description: A poultry farm management app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1

flutter:
  uses-material-design: true


  assets:
    - assets/images/farm_bg.png
    - assets/images/front_title.png
    - assets/images/mannalogo.jpg
